# Generated by Django 6.0.4 on 2026-04-19 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurox_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
