# Generated by Django 6.0.4 on 2026-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurox_core', '0002_user_aadhaar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='constituency',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
