# Generated by Django 6.0.4 on 2026-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurox_core', '0003_user_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('ROAD', 'Road & Transport'), ('WATER', 'Water & Sanitation'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical & Healthcare'), ('ELECTRICITY', 'Electricity & Power'), ('AGRICULTURE', 'Agriculture'), ('HOUSING', 'Housing & Urban Dev'), ('ENVIRONMENT', 'Environment'), ('LAW_ORDER', 'Law & Order'), ('WELFARE', 'Social Welfare'), ('EMPLOYMENT', 'Employment'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
