# Generated by Django 6.0.4 on 2026-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurox_core', '0004_post_subject_reaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracking',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open/Unassigned'), ('UNDER_VERIFICATION', 'Under Verification'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
