from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils import timezone

class User(AbstractUser):
    """
    Custom user model including specific area location and Aadhaar identity tracking.
    """
    area = models.CharField(max_length=255, blank=True)  # District
    constituency = models.CharField(max_length=255, blank=True)  # Assembly constituency
    name = models.CharField(max_length=255, blank=True)
    
    aadhaar_validator = RegexValidator(
        regex=r'^\d{12}$',
        message='Aadhaar number must be exactly 12 digits.'
    )
    aadhaar_id = models.CharField(
        max_length=12, 
        validators=[aadhaar_validator], 
        unique=True, 
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.username

class Department(models.Model):
    """
    Representation of state or city level departments (e.g., Water Board, Transportation).
    """
    name = models.CharField(max_length=255, unique=True)
    contact_email = models.EmailField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    """
    State development ideas and petitions generated by users.
    """
    PRIORITY_CHOICES = (
        ('NORMAL', 'Normal'),
        ('IMPORTANT', 'Important (>= 10k Supports)'),
        ('URGENT', 'Urgent (>= 50k Supports)'),
    )

    SUBJECT_CHOICES = (
        ('ROAD', 'Road & Transport'),
        ('WATER', 'Water & Sanitation'),
        ('EDUCATION', 'Education'),
        ('MEDICAL', 'Medical & Healthcare'),
        ('ELECTRICITY', 'Electricity & Power'),
        ('AGRICULTURE', 'Agriculture'),
        ('HOUSING', 'Housing & Urban Dev'),
        ('ENVIRONMENT', 'Environment'),
        ('LAW_ORDER', 'Law & Order'),
        ('WELFARE', 'Social Welfare'),
        ('EMPLOYMENT', 'Employment'),
        ('OTHER', 'Other'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    area = models.CharField(max_length=255)
    subject = models.CharField(max_length=30, choices=SUBJECT_CHOICES, default='OTHER')
    problem_statement = models.TextField()
    
    support_count = models.PositiveIntegerField(default=0)
    unsupport_count = models.PositiveIntegerField(default=0)
    share_count = models.PositiveIntegerField(default=0)
    
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='NORMAL')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.author.username}'s post in {self.area}"

class Reaction(models.Model):
    """
    Individual user reaction to track whether they have Supported or Unsupported a post.
    """
    REACTION_CHOICES = (
        ('SUPPORT', 'Support'),
        ('UNSUPPORT', 'Unsupport'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reactions')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reactions')
    reaction_type = models.CharField(max_length=20, choices=REACTION_CHOICES)
    reason = models.TextField(blank=True, default='')  # Required for UNSUPPORT
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post') # User can only react once per post

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class IssueTracking(models.Model):
    """
    Jira-like workflow board to track the resolution progress of an escalated Post.
    """
    STATUS_CHOICES = (
        ('OPEN', 'Open/Unassigned'),
        ('UNDER_VERIFICATION', 'Under Verification'),
        ('IN_PROGRESS', 'In Progress'),
        ('RESOLVED', 'Resolved'),
        ('CLOSED', 'Closed'),
    )

    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name='issue_tracking')
    assigned_department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_issues')
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='OPEN')
    sla_deadline = models.DateTimeField(null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Issue tracking for Post #{self.post.id} - {self.status}"
